version: '3'

services:
  database:
    build:
      context: ../Banco-IT_Talent/
    container_name: it-talent-desafio-junho-database
    # image: it-talent-desafio-junho-database
    ports:
      - "3306:3036"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: BANCO_DADOS_IT_TALENT
  backend:
    build:
      context: .
    container_name: it-talent-desafio-junho-backend
    # image: it-talent-desafio-junho-backend
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: BANCO_DADOS_IT_TALENT
